// <auto-generated />
namespace NPL_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Service_ManytoMany_AgencyUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Service_ManytoMany_AgencyUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201610150225024_Service_ManytoMany_AgencyUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
